/* Generated by tools/bake-pets.mjs. Frame i of assets/art/pet-<id>.png sits at
   x = i * (w + gutter); frames: idle, blink, happy, talk, sleep. `feet` is where
   the two feet are in the idle frame (sheet px): they step on their own when a
   pet walks (src/pets/sprite.js). BABY_SHEETS are pet-<id>-baby.png (--baby). */
export const SHEETS = {
  toffee: { w: 246, h: 384, gutter: 4, frames: 5, feet: { top: 361, bottom: 378, split: 144 } },
  chai: { w: 305, h: 384, gutter: 4, frames: 5, feet: { top: 356, bottom: 377, split: 173 } },
  matcha: { w: 259, h: 384, gutter: 4, frames: 5, feet: { top: 362, bottom: 377, split: 141 } },
  mochi: { w: 348, h: 384, gutter: 4, frames: 5, feet: { top: 352, bottom: 376, split: 184 } },
  ginger: { w: 351, h: 384, gutter: 4, frames: 5, feet: { top: 358, bottom: 376, split: 150 } },
  mallow: { w: 329, h: 384, gutter: 4, frames: 5, feet: { top: 359, bottom: 377, split: 131 } },
};
export const BABY_SHEETS = {
  toffee: { w: 206, h: 288, gutter: 4, frames: 5, feet: { top: 274, bottom: 284, split: 121 } },
  chai: { w: 266, h: 288, gutter: 4, frames: 5, feet: { top: 270, bottom: 283, split: 151 } },
  matcha: { w: 215, h: 288, gutter: 4, frames: 5, feet: { top: 274, bottom: 283, split: 114 } },
  mochi: { w: 301, h: 288, gutter: 4, frames: 5, feet: { top: 268, bottom: 283, split: 159 } },
  ginger: { w: 303, h: 288, gutter: 4, frames: 5, feet: { top: 272, bottom: 283, split: 130 } },
  mallow: { w: 277, h: 288, gutter: 4, frames: 5, feet: { top: 272, bottom: 283, split: 110 } },
};
