/* Generated by tools/bake-pets.mjs. Frame i of assets/art/pet-<id>.png sits at
   x = i * (w + gutter); frames: idle, blink, happy, talk, sleep. `feet` is where
   the two feet are in the idle frame (sheet px): they step on their own when a
   pet walks (src/pets/sprite.js). */
export const SHEETS = {
  toffee: { w: 246, h: 384, gutter: 4, frames: 5, feet: { top: 361, bottom: 378, split: 144 } },
  chai: { w: 305, h: 384, gutter: 4, frames: 5, feet: { top: 356, bottom: 377, split: 173 } },
  matcha: { w: 259, h: 384, gutter: 4, frames: 5, feet: { top: 362, bottom: 377, split: 141 } },
  mochi: { w: 348, h: 384, gutter: 4, frames: 5, feet: { top: 352, bottom: 376, split: 184 } },
  ginger: { w: 351, h: 384, gutter: 4, frames: 5, feet: { top: 358, bottom: 376, split: 150 } },
  mallow: { w: 329, h: 384, gutter: 4, frames: 5, feet: { top: 359, bottom: 377, split: 131 } },
};
