/* Generated by tools/bake-pets.mjs. Frame i of assets/art/pet-<id>.png sits at
   x = i * (w + gutter); frames: idle, blink, happy, talk, sleep. */
export const SHEETS = {
  toffee: { w: 164, h: 256, gutter: 4, frames: 5 },
  chai: { w: 204, h: 256, gutter: 4, frames: 5 },
  matcha: { w: 173, h: 256, gutter: 4, frames: 5 },
  mochi: { w: 232, h: 256, gutter: 4, frames: 5 },
  ginger: { w: 234, h: 256, gutter: 4, frames: 5 },
  mallow: { w: 219, h: 256, gutter: 4, frames: 5 },
};
