/**
 * service-worker.js — offline caching for CAT OS.
 *
 * WHAT CHANGED IN 2.1.2, AND WHY.
 *
 * The old worker did this at install:
 *
 *     Promise.all([ shell.addAll(168 files), content.addAll(426 files) ])
 *
 * `addAll` is all-or-nothing. One dropped request on patchy mobile data —
 * one, out of five hundred and ninety-four — and the whole install rejects,
 * NOTHING is cached, and the learner who thought they had downloaded the app
 * finds an empty screen on the train. Worse, a CONTENT_VERSION bump deleted
 * the entire content cache on activate, including the library that
 * library-sync.js had spent the learner's mobile data fetching, before the
 * replacement existed.
 *
 * This worker installs in stages and can always resume.
 *
 *   CORE     the shell, the router, the storage, the village: what the first
 *            frame needs and nothing else. Cached at install, per file, with
 *            retries. Install completes if the core is there.
 *   SHELL    every other screen and module. Filled in the background after
 *            activate, in small batches.
 *   CONTENT  the registry, the schemas and the reference bundles. Same.
 *   BANKS    passages, jumbles, summaries, placement, completion, the word
 *            bank and arguments — a couple of thousand files — are never
 *            precached: the fetch handler keeps each one the first time it is
 *            asked for, and library-sync.js walks content/manifest.json in
 *            idle time.
 *
 * THE CACHE IS THE CHECKPOINT. Nothing tracks which files are done, because
 * `cache.keys()` already knows. A fill pass asks what is missing and fetches
 * only that, so an install interrupted at file 300 of 594 resumes at 300 —
 * whether it was interrupted by a closed tab, a dead connection or a reboot.
 * Only the failure count and the backoff clock are persisted (in a tiny
 * cat-os-meta cache, because a worker has no localStorage).
 *
 * A VERSION CHANGE NEVER DESTROYS A WORKING LIBRARY. When CONTENT_VERSION
 * moves, the new cache is filled alongside the old one. Reads try the new
 * cache, then the old, so a half-filled upgrade still serves every file the
 * learner already had. The old cache is deleted only once the new one is
 * provably complete — that is the promotion, and it is the only moment
 * anything is thrown away. If the upgrade never completes, the learner keeps
 * the version that works, for as long as it takes.
 *
 * NOTHING BROKEN IS EVER KEPT. A response is cached only if it is `ok`; a
 * 404 page or a captive-portal login screen stored under a passage's URL is
 * exactly the corruption that makes an offline app fail in ways nobody can
 * explain. The page can also report a file that parsed as garbage
 * (`postMessage({type:'catos:evict'})`) and the worker drops it, so the next
 * read re-fetches it.
 *
 * Strategy is otherwise unchanged: cache-first (TECH_STACK.md), guaranteed
 * offline startup, new versions on the second load after a deploy.
 *
 * All paths are RELATIVE so the worker functions from a GitHub Pages
 * subpath. `self.registration.scope` resolves them correctly.
 *
 * tools/build-precache.mjs rewrites CORE_FILES and CONTENT_FILES from disk.
 * verify.mjs checks that every module the app imports is in one of the lists.
 */

const CACHE_VERSION = 40;
const CONTENT_VERSION = 15;
/* Written by tools/build-precache.mjs: a hash of the CONTENT of every file
   in each list. The cache name carries it, so a release that changes a file
   ALWAYS lands in a new cache, whether or not anybody remembered to bump the
   number above. Nothing used to enforce that bump, and an installed learner
   could sit on old code forever with no symptom anybody could see. */
const BUILD_ID = '0b0fafe5f8';
const CONTENT_ID = 'f745ea6466';
const SHELL_CACHE = `cat-os-shell-v${CACHE_VERSION}.${BUILD_ID}`;
const CONTENT_CACHE = `cat-os-content-v${CONTENT_VERSION}.${CONTENT_ID}`;
const META_CACHE = 'cat-os-meta';
/* The banks — every passage, jumble, summary, placement, completion, word
   and argument file — live in their OWN cache, and it carries no version.
   They are addressed by a stable id and they are the thing the learner
   actually spent mobile data on; tying them to CONTENT_VERSION would mean
   that shipping one new schema threw away a library that took ten minutes
   to download. A corrected file reaches an installed learner through the
   evict path instead (the reader notices, the worker drops it, the next
   read heals it), which is the only mechanism that can work for content
   nobody precaches. */
const LIBRARY_CACHE = 'cat-os-library';

/* How much is fetched at once, and how hard we try. Twelve is enough to keep
   a connection busy and few enough that a phone on 3G is not swamped while
   the learner is reading. */
const BATCH = 12;
const TRIES = 3;

/* Stage 1 — the install must get these. Generated by tools/build-precache.mjs
   from the real import graph: everything a cold open of the village fetches
   before it can paint. */
const CORE_FILES = [
  './',
  './index.html',
  './manifest.webmanifest',
  './src/ui/styles/tokens.css',
  './src/ui/styles/base.css',
  './src/ui/styles/components.css',
  './src/ui/styles/game.css',
  './src/ui/styles/world.css',
  './src/ui/styles/village.css',
  './src/ui/styles/home-world.css',
  './assets/art/home-world-v1.png',
  './assets/art/home-companions-v1.png',
  './content/boot-index.json',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './src/app.js',
  './src/core/content-loader/library-sync.js',
  './src/core/content-loader/loader.js',
  './src/core/content-loader/validator.js',
  './src/core/engagement/audio.js',
  './src/core/engagement/feedback.js',
  './src/core/engagement/stats.js',
  './src/core/engagement/streaks.js',
  './src/core/engagement/xp.js',
  './src/core/engine/garden-session.js',
  './src/core/learning/journey.js',
  './src/core/learning/review.js',
  './src/core/learning/taxonomy.js',
  './src/core/router/router.js',
  './src/core/storage/indexeddb-adapter.js',
  './src/core/storage/storage-adapter.js',
  './src/core/utils/format.js',
  './src/home/cards.js',
  './src/home/life.js',
  './src/home/motion-atlas.js',
  './src/home/motion.js',
  './src/home/village.js',
  './src/modules/language-garden/index.js',
  './src/modules/language-garden/logic/effort.js',
  './src/modules/language-garden/logic/groves.js',
  './src/modules/odd-one-out/index.js',
  './src/modules/para-jumbles/index.js',
  './src/modules/para-summary/index.js',
  './src/modules/reading-comprehension/index.js',
  './src/modules/verbal-bank/index.js',
  './src/modules/word-dna/index.js',
  './src/pets/economy.js',
  './src/pets/next.js',
  './src/pets/paths.js',
  './src/pets/pets.js',
  './src/pets/sheets.js',
  './src/pets/sprite.js',
  './src/shell/prefs.js',
  './src/ui/components/cat-nav.js',
  './src/ui/components/cat-toast.js',
  './src/ui/modal.js',
  './src/village/art.js',
  './src/village/defs.js',
  './src/village/living-art.js',
  './src/village/sprites.js',
  './src/world/audio.js',
  './src/world/companion.js',
  './src/world/curator.js',
  './src/world/economy.js',
  './src/world/engine/palette.js',
  './src/world/growth.js',
  './src/world/index.js',
  './src/world/lexicon.js',
  './src/world/stage.js',
  './src/world/state.js',
];

/* Stage 2 — every other screen and module, filled after activate. */
const SHELL_FILES = [
  './',
  './assets/art/bench.png',
  './assets/art/books.png',
  './assets/art/bush.png',
  './assets/art/crate.png',
  './assets/art/fence.png',
  './assets/art/flowers.png',
  './assets/art/grass.png',
  './assets/art/hearth_L1.png',
  './assets/art/hearth_L2.png',
  './assets/art/hearth_L3.png',
  './assets/art/hearth_L4.png',
  './assets/art/hearth_L5.png',
  './assets/art/home-companions-v1.png',
  './assets/art/home-motion-v1.png',
  './assets/art/home-world-v1.png',
  './assets/art/lamp.png',
  './assets/art/pathTile.png',
  './assets/art/pet-chai.png',
  './assets/art/pet-ginger.png',
  './assets/art/pet-mallow.png',
  './assets/art/pet-matcha.png',
  './assets/art/pet-mochi.png',
  './assets/art/pet-toffee.png',
  './assets/art/planter.png',
  './assets/art/pond.png',
  './assets/art/reading_L1.png',
  './assets/art/reading_L2.png',
  './assets/art/reading_L3.png',
  './assets/art/reading_L4.png',
  './assets/art/rock.png',
  './assets/art/sign.png',
  './assets/art/tree_birch.png',
  './assets/art/tree_oak.png',
  './assets/art/tree_pine.png',
  './assets/art/wick_celebrate_00.png',
  './assets/art/wick_celebrate_01.png',
  './assets/art/wick_celebrate_02.png',
  './assets/art/wick_celebrate_03.png',
  './assets/art/wick_celebrate_04.png',
  './assets/art/wick_celebrate_05.png',
  './assets/art/wick_celebrate_06.png',
  './assets/art/wick_celebrate_07.png',
  './assets/art/wick_idle_00.png',
  './assets/art/wick_idle_01.png',
  './assets/art/wick_idle_02.png',
  './assets/art/wick_idle_03.png',
  './assets/art/wick_idle_04.png',
  './assets/art/wick_idle_05.png',
  './assets/art/wick_idle_06.png',
  './assets/art/wick_idle_07.png',
  './assets/art/wick_read_00.png',
  './assets/art/wick_read_01.png',
  './assets/art/wick_read_02.png',
  './assets/art/wick_read_03.png',
  './assets/art/wick_read_04.png',
  './assets/art/wick_read_05.png',
  './assets/art/wick_read_06.png',
  './assets/art/wick_read_07.png',
  './assets/art/wick_sleep_00.png',
  './assets/art/wick_sleep_01.png',
  './assets/art/wick_sleep_02.png',
  './assets/art/wick_sleep_03.png',
  './assets/art/wick_sleep_04.png',
  './assets/art/wick_sleep_05.png',
  './assets/art/wick_sleep_06.png',
  './assets/art/wick_sleep_07.png',
  './assets/art/wick_walk_00.png',
  './assets/art/wick_walk_01.png',
  './assets/art/wick_walk_02.png',
  './assets/art/wick_walk_03.png',
  './assets/art/wick_walk_04.png',
  './assets/art/wick_walk_05.png',
  './assets/art/wick_walk_06.png',
  './assets/art/wick_walk_07.png',
  './assets/icons/apple-touch-icon.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/maskable-512.png',
  './content/boot-index.json',
  './index.html',
  './manifest.webmanifest',
  './src/app.js',
  './src/core/content-loader/library-sync.js',
  './src/core/content-loader/loader.js',
  './src/core/content-loader/validator.js',
  './src/core/engagement/achievements.js',
  './src/core/engagement/audio.js',
  './src/core/engagement/feedback.js',
  './src/core/engagement/messages.js',
  './src/core/engagement/stats.js',
  './src/core/engagement/streaks.js',
  './src/core/engagement/xp.js',
  './src/core/engine/bank-session.js',
  './src/core/engine/draft-shape.js',
  './src/core/engine/garden-gate.js',
  './src/core/engine/garden-session.js',
  './src/core/engine/ooo-session.js',
  './src/core/engine/pj-session.js',
  './src/core/engine/ps-session.js',
  './src/core/engine/scoring.js',
  './src/core/engine/session.js',
  './src/core/engine/wd-session.js',
  './src/core/learning/draft.js',
  './src/core/learning/journey.js',
  './src/core/learning/noticing.js',
  './src/core/learning/review.js',
  './src/core/learning/taxonomy.js',
  './src/core/mentor/dna.js',
  './src/core/mentor/garden-voice.js',
  './src/core/mentor/lesson.js',
  './src/core/mentor/ooo-dna.js',
  './src/core/mentor/ooo-lesson.js',
  './src/core/mentor/ooo-voice.js',
  './src/core/mentor/pj-dna.js',
  './src/core/mentor/pj-lesson.js',
  './src/core/mentor/pj-voice.js',
  './src/core/mentor/ps-dna.js',
  './src/core/mentor/ps-lesson.js',
  './src/core/mentor/ps-voice.js',
  './src/core/mentor/records.js',
  './src/core/mentor/voice.js',
  './src/core/mentor/wd-dna.js',
  './src/core/mentor/wd-lesson.js',
  './src/core/mentor/wd-voice.js',
  './src/core/router/router.js',
  './src/core/storage/backup.js',
  './src/core/storage/indexeddb-adapter.js',
  './src/core/storage/storage-adapter.js',
  './src/core/utils/format.js',
  './src/home/cards.js',
  './src/home/life.js',
  './src/home/motion-atlas.js',
  './src/home/motion.js',
  './src/home/village.js',
  './src/modules/language-garden/index.js',
  './src/modules/language-garden/logic/atmosphere.js',
  './src/modules/language-garden/logic/audio.js',
  './src/modules/language-garden/logic/biomes.js',
  './src/modules/language-garden/logic/effort.js',
  './src/modules/language-garden/logic/groves.js',
  './src/modules/language-garden/logic/scene.js',
  './src/modules/language-garden/logic/store.js',
  './src/modules/language-garden/screens/plant.js',
  './src/modules/language-garden/screens/session.js',
  './src/modules/odd-one-out/index.js',
  './src/modules/odd-one-out/logic/store.js',
  './src/modules/odd-one-out/logic/teach.js',
  './src/modules/odd-one-out/logic/think.js',
  './src/modules/odd-one-out/logic/tiers.js',
  './src/modules/odd-one-out/screens/browser.js',
  './src/modules/odd-one-out/screens/intro.js',
  './src/modules/odd-one-out/screens/learn.js',
  './src/modules/odd-one-out/screens/session.js',
  './src/modules/para-jumbles/index.js',
  './src/modules/para-jumbles/logic/store.js',
  './src/modules/para-jumbles/logic/teach.js',
  './src/modules/para-jumbles/logic/tiers.js',
  './src/modules/para-jumbles/screens/browser.js',
  './src/modules/para-jumbles/screens/intro.js',
  './src/modules/para-jumbles/screens/learn.js',
  './src/modules/para-jumbles/screens/session.js',
  './src/modules/para-summary/index.js',
  './src/modules/para-summary/logic/store.js',
  './src/modules/para-summary/logic/teach.js',
  './src/modules/para-summary/logic/think.js',
  './src/modules/para-summary/logic/tiers.js',
  './src/modules/para-summary/screens/browser.js',
  './src/modules/para-summary/screens/intro.js',
  './src/modules/para-summary/screens/learn.js',
  './src/modules/para-summary/screens/session.js',
  './src/modules/reading-comprehension/index.js',
  './src/modules/reading-comprehension/logic/spoilers.js',
  './src/modules/reading-comprehension/logic/store.js',
  './src/modules/reading-comprehension/screens/browser.js',
  './src/modules/reading-comprehension/screens/mentor.js',
  './src/modules/reading-comprehension/screens/review.js',
  './src/modules/reading-comprehension/screens/second-look.js',
  './src/modules/reading-comprehension/screens/session.js',
  './src/modules/verbal-bank/index.js',
  './src/modules/verbal-bank/screens/session.js',
  './src/modules/word-dna/index.js',
  './src/modules/word-dna/logic/garden.js',
  './src/modules/word-dna/logic/store.js',
  './src/modules/word-dna/logic/tree.js',
  './src/modules/word-dna/screens/garden.js',
  './src/modules/word-dna/screens/intro.js',
  './src/modules/word-dna/screens/learn.js',
  './src/modules/word-dna/screens/session.js',
  './src/modules/word-dna/screens/tree.js',
  './src/pets/economy.js',
  './src/pets/next.js',
  './src/pets/paths.js',
  './src/pets/pets.js',
  './src/pets/sheets.js',
  './src/pets/sprite.js',
  './src/shell/growth.js',
  './src/shell/prefs.js',
  './src/shell/settings.js',
  './src/ui/components/cat-briefing.js',
  './src/ui/components/cat-celebration.js',
  './src/ui/components/cat-explanation.js',
  './src/ui/components/cat-jumble-board.js',
  './src/ui/components/cat-nav.js',
  './src/ui/components/cat-option.js',
  './src/ui/components/cat-passage.js',
  './src/ui/components/cat-plant.js',
  './src/ui/components/cat-progress-bar.js',
  './src/ui/components/cat-question-card.js',
  './src/ui/components/cat-reflection.js',
  './src/ui/components/cat-result-summary.js',
  './src/ui/components/cat-timer.js',
  './src/ui/components/cat-toast.js',
  './src/ui/components/cat-week-strip.js',
  './src/ui/components/cat-xp-bar.js',
  './src/ui/modal.js',
  './src/ui/styles/base.css',
  './src/ui/styles/components.css',
  './src/ui/styles/game.css',
  './src/ui/styles/home-world.css',
  './src/ui/styles/home.css',
  './src/ui/styles/rewards.css',
  './src/ui/styles/tokens.css',
  './src/ui/styles/village.css',
  './src/ui/styles/world.css',
  './src/village/art.js',
  './src/village/defs.js',
  './src/village/grove.js',
  './src/village/life.js',
  './src/village/living-art.js',
  './src/village/next.js',
  './src/village/renderer.js',
  './src/village/scene.js',
  './src/village/screens/home-world.js',
  './src/village/screens/village.js',
  './src/village/sprites.js',
  './src/village/state.js',
  './src/village/terrain.js',
  './src/world/audio.js',
  './src/world/collections.js',
  './src/world/companion.js',
  './src/world/curator.js',
  './src/world/economy.js',
  './src/world/engine/palette.js',
  './src/world/growth.js',
  './src/world/icons.js',
  './src/world/index.js',
  './src/world/lexicon.js',
  './src/world/menu.js',
  './src/world/regions.js',
  './src/world/rewards.js',
  './src/world/screens/hearth.js',
  './src/world/screens/place.js',
  './src/world/screens/result.js',
  './src/world/screens/round.js',
  './src/world/screens/wilds.js',
  './src/world/stage.js',
  './src/world/state.js',
];

const CONTENT_FILES = [
  './content/boot-index.json',
  './content/index.json',
  './content/manifest.json',
  './content/context/pack.json',
  './content/schema/cr.schema.v1.json',
  './content/schema/lex.schema.v1.json',
  './content/schema/lg.schema.v1.json',
  './content/schema/loan.schema.v1.json',
  './content/schema/ooo.schema.v1.json',
  './content/schema/ooo.schema.v2.json',
  './content/schema/pc.schema.v1.json',
  './content/schema/pj.schema.v1.json',
  './content/schema/pj.schema.v2.json',
  './content/schema/ps.schema.v1.json',
  './content/schema/ps.schema.v2.json',
  './content/schema/rc.schema.v1.json',
  './content/schema/rc.schema.v2.json',
  './content/schema/rc.schema.v3.json',
  './content/schema/rc.schema.v4.json',
  './content/schema/rc.schema.v5.json',
  './content/schema/sp.schema.v1.json',
  './content/schema/twin.schema.v1.json',
  './content/schema/vocab.schema.v1.json',
  './content/schema/wb.schema.v1.json',
  './content/schema/wd.schema.v1.json',
  './content/vocabulary/vocab-0001.json',
  './content/vocabulary/vocab-0002.json',
  './content/vocabulary/vocab-0003.json',
  './content/vocabulary/vocab-0004.json',
  './content/vocabulary/vocab-0005.json',
  './content/vocabulary/vocab-0006.json',
  './content/vocabulary/vocab-0007.json',
  './content/vocabulary/vocab-0008.json',
  './content/vocabulary/vocab-0009.json',
  './content/vocabulary/vocab-0010.json',
  './content/vocabulary/vocab-0011.json',
  './content/vocabulary/vocab-0012.json',
  './content/vocabulary/vocab-0013.json',
  './content/vocabulary/vocab-0014.json',
  './content/vocabulary/vocab-0015.json',
  './content/vocabulary/vocab-0016.json',
  './content/vocabulary/vocab-0017.json',
  './content/vocabulary/vocab-0018.json',
  './content/vocabulary/vocab-0019.json',
  './content/vocabulary/vocab-0020.json',
  './content/vocabulary/vocab-0021.json',
  './content/vocabulary/vocab-0022.json',
  './content/vocabulary/vocab-0023.json',
  './content/vocabulary/vocab-0024.json',
  './content/vocabulary/vocab-0025.json',
  './content/vocabulary/vocab-0026.json',
  './content/vocabulary/vocab-0027.json',
  './content/vocabulary/vocab-0028.json',
  './content/vocabulary/vocab-0029.json',
  './content/vocabulary/vocab-0030.json',
  './content/vocabulary/vocab-0031.json',
  './content/vocabulary/vocab-0032.json',
  './content/vocabulary/vocab-0033.json',
  './content/vocabulary/vocab-0034.json',
  './content/vocabulary/vocab-0035.json',
  './content/vocabulary/vocab-0036.json',
  './content/vocabulary/vocab-0037.json',
  './content/vocabulary/vocab-0038.json',
  './content/vocabulary/vocab-0039.json',
  './content/vocabulary/vocab-0040.json',
  './content/vocabulary/vocab-0041.json',
  './content/vocabulary/vocab-0042.json',
  './content/vocabulary/vocab-0043.json',
  './content/vocabulary/vocab-0044.json',
  './content/vocabulary/vocab-0045.json',
  './content/vocabulary/vocab-0046.json',
  './content/vocabulary/vocab-0047.json',
  './content/vocabulary/vocab-0048.json',
  './content/vocabulary/vocab-0049.json',
  './content/vocabulary/vocab-0050.json',
  './content/vocabulary/vocab-0051.json',
  './content/vocabulary/vocab-0052.json',
  './content/vocabulary/vocab-0053.json',
  './content/vocabulary/vocab-0054.json',
  './content/vocabulary/vocab-0055.json',
  './content/vocabulary/vocab-0056.json',
  './content/vocabulary/vocab-0057.json',
  './content/vocabulary/vocab-0058.json',
  './content/vocabulary/vocab-0059.json',
  './content/vocabulary/vocab-0060.json',
  './content/vocabulary/vocab-0061.json',
  './content/vocabulary/vocab-0062.json',
  './content/vocabulary/vocab-0063.json',
  './content/vocabulary/vocab-0064.json',
  './content/vocabulary/vocab-0065.json',
  './content/vocabulary/vocab-0066.json',
  './content/vocabulary/vocab-0067.json',
  './content/vocabulary/vocab-0068.json',
  './content/vocabulary/vocab-0069.json',
  './content/vocabulary/vocab-0070.json',
  './content/vocabulary/vocab-0071.json',
  './content/vocabulary/vocab-0072.json',
  './content/vocabulary/vocab-0073.json',
  './content/vocabulary/vocab-0074.json',
  './content/vocabulary/vocab-0075.json',
  './content/vocabulary/vocab-0076.json',
  './content/vocabulary/vocab-0077.json',
  './content/vocabulary/vocab-0078.json',
  './content/vocabulary/vocab-0079.json',
  './content/vocabulary/vocab-0080.json',
  './content/vocabulary/vocab-0081.json',
  './content/vocabulary/vocab-0082.json',
  './content/vocabulary/vocab-0083.json',
  './content/vocabulary/vocab-0084.json',
  './content/vocabulary/vocab-0085.json',
  './content/vocabulary/vocab-0086.json',
  './content/vocabulary/vocab-0087.json',
  './content/vocabulary/vocab-0088.json',
  './content/vocabulary/vocab-0089.json',
  './content/vocabulary/vocab-0090.json',
  './content/vocabulary/vocab-0091.json',
  './content/vocabulary/vocab-0092.json',
  './content/vocabulary/vocab-0093.json',
  './content/vocabulary/vocab-0094.json',
  './content/vocabulary/vocab-0095.json',
  './content/vocabulary/vocab-0096.json',
  './content/vocabulary/vocab-0097.json',
  './content/vocabulary/vocab-0098.json',
  './content/vocabulary/vocab-0099.json',
  './content/vocabulary/vocab-0100.json',
  './content/vocabulary/vocab-0101.json',
  './content/vocabulary/vocab-0102.json',
  './content/vocabulary/vocab-0103.json',
  './content/vocabulary/vocab-0104.json',
  './content/vocabulary/vocab-0105.json',
  './content/vocabulary/vocab-0106.json',
  './content/vocabulary/vocab-0107.json',
  './content/vocabulary/vocab-0108.json',
  './content/vocabulary/vocab-0109.json',
  './content/vocabulary/vocab-0110.json',
  './content/vocabulary/vocab-0111.json',
  './content/vocabulary/vocab-0112.json',
  './content/vocabulary/vocab-0113.json',
  './content/vocabulary/vocab-0114.json',
  './content/vocabulary/vocab-0115.json',
  './content/vocabulary/vocab-0116.json',
  './content/vocabulary/vocab-0117.json',
  './content/vocabulary/vocab-0118.json',
  './content/vocabulary/vocab-0119.json',
  './content/vocabulary/vocab-0120.json',
  './content/vocabulary/vocab-0121.json',
  './content/vocabulary/vocab-0122.json',
  './content/vocabulary/vocab-0123.json',
  './content/vocabulary/vocab-0124.json',
  './content/vocabulary/vocab-0125.json',
  './content/vocabulary/vocab-0126.json',
  './content/vocabulary/vocab-0127.json',
  './content/vocabulary/vocab-0128.json',
  './content/vocabulary/vocab-0129.json',
  './content/vocabulary/vocab-0130.json',
  './content/vocabulary/vocab-0131.json',
  './content/vocabulary/vocab-0132.json',
  './content/vocabulary/vocab-0133.json',
  './content/vocabulary/vocab-0134.json',
  './content/vocabulary/vocab-0135.json',
  './content/vocabulary/vocab-0136.json',
  './content/vocabulary/vocab-0137.json',
  './content/vocabulary/vocab-0138.json',
  './content/vocabulary/vocab-0139.json',
  './content/vocabulary/vocab-0140.json',
  './content/vocabulary/vocab-0141.json',
  './content/vocabulary/vocab-0142.json',
  './content/vocabulary/vocab-0143.json',
  './content/vocabulary/vocab-0144.json',
  './content/vocabulary/vocab-0145.json',
  './content/vocabulary/vocab-0146.json',
  './content/vocabulary/vocab-0147.json',
  './content/vocabulary/vocab-0148.json',
  './content/vocabulary/vocab-0149.json',
  './content/vocabulary/vocab-0150.json',
  './content/vocabulary/vocab-0151.json',
  './content/vocabulary/vocab-0152.json',
  './content/vocabulary/vocab-0153.json',
  './content/vocabulary/vocab-0154.json',
  './content/vocabulary/vocab-0155.json',
  './content/vocabulary/vocab-0156.json',
  './content/vocabulary/vocab-0157.json',
  './content/vocabulary/vocab-0158.json',
  './content/vocabulary/vocab-0159.json',
  './content/vocabulary/vocab-0160.json',
  './content/vocabulary/vocab-0161.json',
  './content/vocabulary/vocab-0162.json',
  './content/vocabulary/vocab-0163.json',
  './content/vocabulary/vocab-0164.json',
  './content/vocabulary/vocab-0165.json',
  './content/vocabulary/vocab-0166.json',
  './content/vocabulary/vocab-0167.json',
  './content/vocabulary/vocab-0168.json',
  './content/vocabulary/vocab-0169.json',
  './content/vocabulary/vocab-0170.json',
  './content/vocabulary/vocab-0171.json',
  './content/vocabulary/vocab-0172.json',
  './content/vocabulary/vocab-0173.json',
  './content/vocabulary/vocab-0174.json',
  './content/vocabulary/vocab-0175.json',
  './content/vocabulary/vocab-0176.json',
  './content/vocabulary/vocab-0177.json',
  './content/vocabulary/vocab-0178.json',
  './content/vocabulary/vocab-0179.json',
  './content/vocabulary/vocab-0180.json',
  './content/vocabulary/vocab-0181.json',
  './content/vocabulary/vocab-0182.json',
  './content/vocabulary/vocab-0183.json',
  './content/vocabulary/vocab-0184.json',
  './content/vocabulary/vocab-0185.json',
  './content/vocabulary/vocab-0186.json',
  './content/vocabulary/vocab-0187.json',
  './content/vocabulary/vocab-0188.json',
  './content/vocabulary/vocab-0189.json',
  './content/vocabulary/vocab-0190.json',
  './content/vocabulary/vocab-0191.json',
  './content/vocabulary/vocab-0192.json',
  './content/vocabulary/vocab-0193.json',
  './content/vocabulary/vocab-0194.json',
  './content/vocabulary/vocab-0195.json',
  './content/vocabulary/vocab-0196.json',
  './content/vocabulary/vocab-0197.json',
  './content/vocabulary/vocab-0198.json',
  './content/vocabulary/vocab-0199.json',
  './content/vocabulary/vocab-0200.json',
  './content/vocabulary/vocab-0201.json',
  './content/vocabulary/vocab-0202.json',
  './content/vocabulary/vocab-0203.json',
  './content/vocabulary/vocab-0204.json',
  './content/vocabulary/vocab-0205.json',
  './content/vocabulary/vocab-0206.json',
  './content/vocabulary/vocab-0207.json',
  './content/vocabulary/vocab-0208.json',
  './content/vocabulary/vocab-0209.json',
  './content/vocabulary/vocab-0210.json',
  './content/vocabulary/vocab-0211.json',
  './content/vocabulary/vocab-0212.json',
  './content/vocabulary/vocab-0213.json',
  './content/vocabulary/vocab-0214.json',
  './content/vocabulary/vocab-0215.json',
  './content/vocabulary/vocab-0216.json',
  './content/vocabulary/vocab-0217.json',
  './content/language-garden/lg-0001.json',
  './content/language-garden/lg-0002.json',
  './content/language-garden/lg-0003.json',
  './content/language-garden/lg-0004.json',
  './content/language-garden/lg-0005.json',
  './content/language-garden/lg-0006.json',
  './content/language-garden/lg-0007.json',
  './content/language-garden/lg-0008.json',
  './content/language-garden/lg-0009.json',
  './content/language-garden/lg-0010.json',
  './content/language-garden/lg-0011.json',
  './content/language-garden/lg-0012.json',
  './content/language-garden/lg-0013.json',
  './content/language-garden/lg-0014.json',
  './content/language-garden/lg-0015.json',
  './content/language-garden/lg-0016.json',
  './content/language-garden/lg-0017.json',
  './content/language-garden/lg-0018.json',
  './content/language-garden/lg-0019.json',
  './content/language-garden/lg-0020.json',
  './content/language-garden/lg-0021.json',
  './content/language-garden/lg-0022.json',
  './content/language-garden/lg-0023.json',
  './content/language-garden/lg-0024.json',
  './content/language-garden/lg-0025.json',
  './content/language-garden/lg-0026.json',
  './content/language-garden/lg-0027.json',
  './content/language-garden/lg-0028.json',
  './content/language-garden/lg-0029.json',
  './content/language-garden/lg-0030.json',
  './content/language-garden/lg-0031.json',
  './content/language-garden/lg-0032.json',
  './content/language-garden/lg-0033.json',
  './content/language-garden/lg-0034.json',
  './content/language-garden/lg-0035.json',
  './content/language-garden/lg-0036.json',
  './content/language-garden/lg-0037.json',
  './content/language-garden/lg-0038.json',
  './content/language-garden/lg-0039.json',
  './content/language-garden/lg-0040.json',
  './content/language-garden/lg-0041.json',
  './content/language-garden/lg-0042.json',
  './content/language-garden/lg-0043.json',
  './content/language-garden/lg-0044.json',
  './content/language-garden/lg-0045.json',
  './content/language-garden/lg-0046.json',
  './content/language-garden/lg-0047.json',
  './content/language-garden/lg-0048.json',
  './content/language-garden/lg-0049.json',
  './content/language-garden/lg-0050.json',
  './content/language-garden/lg-0051.json',
  './content/word-dna/wd-0001.json',
  './content/word-dna/wd-0002.json',
  './content/word-dna/wd-0003.json',
  './content/word-dna/wd-0004.json',
  './content/word-dna/wd-0005.json',
  './content/word-dna/wd-0006.json',
  './content/word-dna/wd-0007.json',
  './content/word-dna/wd-0008.json',
  './content/word-dna/wd-0009.json',
  './content/word-dna/wd-0010.json',
  './content/word-dna/wd-0011.json',
  './content/word-dna/wd-0012.json',
  './content/word-dna/wd-0013.json',
  './content/word-dna/wd-0014.json',
  './content/word-dna/wd-0015.json',
  './content/word-dna/wd-0016.json',
  './content/word-dna/wd-0017.json',
  './content/word-dna/wd-0018.json',
  './content/word-dna/wd-0019.json',
  './content/word-dna/wd-0020.json',
  './content/word-dna/wd-0021.json',
  './content/word-dna/wd-0022.json',
  './content/word-dna/wd-0023.json',
  './content/word-dna/wd-0024.json',
  './content/word-dna/wd-0025.json',
  './content/word-dna/wd-0026.json',
  './content/word-dna/wd-0027.json',
  './content/word-dna/wd-0028.json',
  './content/lexicon/lex-high-a.json',
  './content/lexicon/lex-high-b.json',
  './content/lexicon/lex-high-c.json',
  './content/lexicon/lex-high-d.json',
  './content/lexicon/lex-high-e.json',
  './content/lexicon/lex-high-f.json',
  './content/lexicon/lex-high-g.json',
  './content/lexicon/lex-high-h.json',
  './content/lexicon/lex-high-i.json',
  './content/lexicon/lex-high-j.json',
  './content/lexicon/lex-high-k.json',
  './content/lexicon/lex-high-l.json',
  './content/lexicon/lex-high-m.json',
  './content/lexicon/lex-high-r.json',
  './content/lexicon/lex-high-s.json',
  './content/lexicon/lex-high-t.json',
  './content/lexicon/lex-high-u.json',
  './content/lexicon/lex-high-v.json',
  './content/lexicon/lex-high-w.json',
  './content/lexicon/lex-high-y.json',
  './content/lexicon/lex-high-z.json',
  './content/lexicon/lex-low-a.json',
  './content/lexicon/lex-low-b.json',
  './content/lexicon/lex-low-c.json',
  './content/lexicon/lex-low-d.json',
  './content/lexicon/lex-low-e.json',
  './content/lexicon/lex-low-f.json',
  './content/lexicon/lex-low-g.json',
  './content/lexicon/lex-low-h.json',
  './content/lexicon/lex-low-i.json',
  './content/lexicon/lex-low-j.json',
  './content/lexicon/lex-low-k.json',
  './content/lexicon/lex-low-l.json',
  './content/lexicon/lex-low-m.json',
  './content/lexicon/lex-low-n.json',
  './content/lexicon/lex-low-o.json',
  './content/lexicon/lex-low-p.json',
  './content/lexicon/lex-low-q.json',
  './content/lexicon/lex-low-r.json',
  './content/lexicon/lex-low-s.json',
  './content/lexicon/lex-low-t.json',
  './content/lexicon/lex-low-u.json',
  './content/lexicon/lex-low-v.json',
  './content/lexicon/lex-low-w.json',
  './content/lexicon/lex-low-x.json',
  './content/lexicon/lex-low-z.json',
  './content/lexicon/lex-medium-a.json',
  './content/lexicon/lex-medium-b.json',
  './content/lexicon/lex-medium-c.json',
  './content/lexicon/lex-medium-d.json',
  './content/lexicon/lex-medium-e.json',
  './content/lexicon/lex-medium-f.json',
  './content/lexicon/lex-medium-g.json',
  './content/lexicon/lex-medium-h.json',
  './content/lexicon/lex-medium-i.json',
  './content/lexicon/lex-medium-j.json',
  './content/lexicon/lex-medium-k.json',
  './content/lexicon/lex-medium-l.json',
  './content/lexicon/lex-medium-m.json',
  './content/lexicon/lex-medium-n.json',
  './content/lexicon/lex-medium-o.json',
  './content/lexicon/lex-medium-p.json',
  './content/lexicon/lex-medium-q.json',
  './content/lexicon/lex-medium-r.json',
  './content/lexicon/lex-medium-s.json',
  './content/lexicon/lex-medium-t.json',
  './content/lexicon/lex-medium-u.json',
  './content/lexicon/lex-medium-v.json',
  './content/lexicon/lex-medium-w.json',
  './content/lexicon/lex-medium-y.json',
  './content/lexicon/lex-medium-z.json',
  './content/loanwords/loan-african-languages.json',
  './content/loanwords/loan-arabic.json',
  './content/loanwords/loan-dutch.json',
  './content/loanwords/loan-french.json',
  './content/loanwords/loan-german.json',
  './content/loanwords/loan-indian.json',
  './content/loanwords/loan-italian.json',
  './content/loanwords/loan-japanese.json',
  './content/loanwords/loan-portuguese.json',
  './content/loanwords/loan-russian.json',
  './content/loanwords/loan-spanish.json',
  './content/loanwords/loan-yiddish.json',
  './content/twins/twin-a.json',
  './content/twins/twin-b.json',
  './content/twins/twin-c.json',
  './content/twins/twin-d.json',
  './content/twins/twin-e.json',
  './content/twins/twin-f.json',
  './content/twins/twin-g.json',
  './content/twins/twin-h.json',
  './content/twins/twin-i.json',
  './content/twins/twin-k.json',
  './content/twins/twin-l.json',
  './content/twins/twin-m.json',
  './content/twins/twin-n.json',
  './content/twins/twin-o.json',
  './content/twins/twin-p.json',
  './content/twins/twin-q.json',
  './content/twins/twin-r.json',
  './content/twins/twin-s.json',
  './content/twins/twin-t.json',
  './content/twins/twin-u.json',
  './content/twins/twin-v.json',
  './content/twins/twin-w.json',
  './content/twins/twin-y.json',
];

/* ------------------------------------------------------------------ */
/* Where a file lives                                                  */
/* ------------------------------------------------------------------ */

const isContent = (url) => url.includes('/content/');

/** Absolute URL for a './'-relative precache entry, resolved against scope. */
const abs = (rel) => new URL(rel, self.registration.scope).href;

/* Which content files belong to the versioned precache, and which are library
   banks that must survive every version bump. Built once, lazily, because
   `self.registration.scope` is not available while the module is evaluating. */
let precacheSet = null;
const isPrecachedContent = (url) => {
  if (!precacheSet) precacheSet = new Set(CONTENT_FILES.map(abs));
  return precacheSet.has(url);
};

/* ------------------------------------------------------------------ */
/* Install state (a worker has no localStorage; a cache entry will do)  */
/* ------------------------------------------------------------------ */

const STATE_URL = 'catos-install-state';

async function readState() {
  try {
    const c = await caches.open(META_CACHE);
    const r = await c.match(STATE_URL);
    if (!r) return {};
    return await r.json();
  } catch { return {}; }
}

async function writeState(patch) {
  try {
    const c = await caches.open(META_CACHE);
    const next = { ...(await readState()), ...patch, at: Date.now() };
    await c.put(STATE_URL, new Response(JSON.stringify(next), { headers: { 'content-type': 'application/json' } }));
    return next;
  } catch { return null; }
}

/* ------------------------------------------------------------------ */
/* Filling a cache, resumably                                          */
/* ------------------------------------------------------------------ */

/** What of `files` this cache does not hold yet. One round trip, not N. */
async function missingFrom(cache, files) {
  const have = new Set((await cache.keys()).map((r) => r.url));
  return files.filter((f) => !have.has(abs(f)));
}

/**
 * Fetch one file and keep it — but ONLY if the server actually gave us the
 * file. A 404 body or a portal redirect cached under a passage's URL is the
 * corruption that makes "it works offline" a lie.
 */
async function fetchAndPut(cache, rel) {
  const res = await fetch(abs(rel), { cache: 'no-store', credentials: 'same-origin' });
  if (!res.ok) throw new Error(`${res.status} ${rel}`);
  if (res.type === 'opaqueredirect' || res.redirected) throw new Error(`redirected ${rel}`);
  await cache.put(abs(rel), res.clone());
  return true;
}

/**
 * Fill a cache in batches. Returns what is still missing afterwards, so the
 * caller can decide whether a version is complete. Never throws: a batch that
 * fails leaves its files missing and the next pass picks them up.
 */
async function fill(cacheName, files, { batch = BATCH, signalName = '' } = {}) {
  const cache = await caches.open(cacheName);
  let missing = await missingFrom(cache, files);
  const total = files.length;
  for (let i = 0; i < missing.length; i += batch) {
    const slice = missing.slice(i, i + batch);
    await Promise.all(slice.map(async (rel) => {
      for (let t = 0; t < TRIES; t += 1) {
        try { await fetchAndPut(cache, rel); return; } catch {
          // A short, growing pause: a phone that just lost signal should not
          // spend its battery hammering a dead radio.
          await new Promise((r) => setTimeout(r, 150 * (t + 1) * (t + 1)));
        }
      }
    }));
    if (signalName) {
      await writeState({ [signalName]: { done: total - (await missingFrom(cache, files)).length, total } });
    }
  }
  missing = await missingFrom(cache, files);
  return missing;
}

/* ------------------------------------------------------------------ */
/* Install: the core, and only the core                                */
/* ------------------------------------------------------------------ */

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    // Everything the first frame needs. If some of it cannot be fetched the
    // install still completes — the app works online and the next pass will
    // try again — because refusing to install leaves the learner with no
    // worker at all, which is strictly worse.
    const stillMissing = await fill(SHELL_CACHE, CORE_FILES, { signalName: 'core' });
    await writeState({ phase: 'core', coreMissing: stillMissing.length, shellVersion: CACHE_VERSION, contentVersion: CONTENT_VERSION });
    await self.skipWaiting();
  })());
});

/* ------------------------------------------------------------------ */
/* Activate: claim, then fill the rest in the background               */
/* ------------------------------------------------------------------ */

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // The PREVIOUS shell cache stays. A tab that is open across a deploy is
    // still running the old code, and since 2.1.2 that code loads its screens
    // on demand — so deleting the shell it came from means the next tap on a
    // learning room 404s, offline, with no way back. One generation is kept
    // and the fetch handler falls back to it; the generation before that is
    // safe to drop, because nothing has been running since two deploys ago.
    // Old CONTENT caches are kept for a different reason — see promoteContent.
    const keys = await caches.keys();
    const keep = new Set([SHELL_CACHE, CONTENT_CACHE, META_CACHE, LIBRARY_CACHE]);
    // Which shell was here before this one? The cache names carry a content
    // hash now, so they cannot be ordered by parsing a number out of them —
    // the worker writes its own history instead, and keeps exactly one
    // previous generation.
    const st = await readState();
    const history = [SHELL_CACHE, ...(Array.isArray(st.shellHistory) ? st.shellHistory : [])].filter((k, i, a) => a.indexOf(k) === i).slice(0, 2);
    for (const k of history) keep.add(k);
    await writeState({ shellHistory: history });
    const staleContent = keys.filter((k) => k.startsWith('cat-os-content-v') && !keep.has(k));
    await Promise.all(keys
      .filter((k) => !keep.has(k) && !staleContent.includes(k))
      .map((k) => caches.delete(k)));
    // One-time migration for a device installed before 2.1.2: the banks were
    // living in the versioned content cache, where the next version bump
    // would have deleted them. Move them somewhere that cannot happen.
    await adoptLibraryFrom(staleContent.concat(CONTENT_CACHE));
    await self.clients.claim();
    // Not awaited inside waitUntil beyond this point: activation must not
    // wait on six hundred files.
    fillEverything();
  })());
});

let filling = null;

/**
 * Bring the shell and the content up to date, then promote the content
 * version if it is complete. Safe to call at any time and from anywhere;
 * concurrent calls share one pass.
 */
function fillEverything() {
  if (filling) return filling;
  filling = (async () => {
    try {
      await writeState({ phase: 'shell' });
      await fill(SHELL_CACHE, SHELL_FILES, { signalName: 'shell' });
      await writeState({ phase: 'content' });
      const missing = await fill(CONTENT_CACHE, CONTENT_FILES, { signalName: 'content' });
      if (missing.length === 0) await promoteContent();
      await writeState({ phase: missing.length === 0 ? 'ready' : 'incomplete', contentMissing: missing.length });
    } catch (err) {
      await writeState({ phase: 'retry', lastError: String(err && err.message ? err.message : err).slice(0, 200) });
    } finally {
      filling = null;
    }
  })();
  return filling;
}

/**
 * Take every bank file out of a versioned content cache and put it in the
 * library, which no version bump touches. Runs on activate (for devices
 * installed before the library cache existed) and again before a promotion,
 * so nothing a learner downloaded is ever inside the thing being deleted.
 */
async function adoptLibraryFrom(names) {
  const lib = await caches.open(LIBRARY_CACHE);
  const already = new Set((await lib.keys()).map((r) => r.url));
  for (const name of names) {
    let c;
    try { c = await caches.open(name); } catch { continue; }
    for (const req of await c.keys()) {
      if (isPrecachedContent(req.url) || already.has(req.url)) continue;
      const res = await c.match(req);
      if (res?.ok) { await lib.put(req, res.clone()); already.add(req.url); }
    }
  }
}

/**
 * The only moment anything is thrown away. The new content cache is complete
 * and verified present, and everything the learner downloaded has been moved
 * to the library, so the previous version is finally redundant. Until this
 * runs, reads fall back to it and a half-finished upgrade costs nothing.
 */
async function promoteContent() {
  const keys = await caches.keys();
  const old = keys.filter((k) => k.startsWith('cat-os-content-v') && k !== CONTENT_CACHE);
  if (!old.length) return;
  await adoptLibraryFrom(old);
  await Promise.all(old.map((k) => caches.delete(k)));
  await writeState({ promotedFrom: old, promotedAt: Date.now() });
}

/** Every content cache, newest first: the current one, then older ones. */
async function contentCaches() {
  const keys = (await caches.keys()).filter((k) => k.startsWith('cat-os-content-v'));
  const n = (k) => Number(String(k.slice('cat-os-content-v'.length)).split('.')[0]) || 0;
  return keys.sort((a, b) => (a === CONTENT_CACHE ? -1 : b === CONTENT_CACHE ? 1 : n(b) - n(a)));
}

/* ------------------------------------------------------------------ */
/* Fetch: cache-first, with the previous content version as a fallback */
/* ------------------------------------------------------------------ */

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    // 0.17.0: an exact-URL match. `ignoreSearch` forced a linear scan of every
    // cached entry on every request; nothing in this app fetches with a query
    // string, and a navigation that misses still falls back to the shell.
    const shell = await caches.open(SHELL_CACHE);
    const hit = await shell.match(request);
    if (hit) return hit;

    // A page open across a deploy is still asking for the shell it booted
    // from, and since screens load on demand it will keep asking. The
    // previous generation is still here (see activate) — serve from it.
    if (!isContent(url.pathname)) {
      for (const name of (await caches.keys()).filter((k) => k.startsWith('cat-os-shell-v') && k !== SHELL_CACHE)) {
        const old = await (await caches.open(name)).match(request);
        if (old) return old;
      }
    }

    if (isContent(url.pathname)) {
      // The library first (it holds everything the learner downloaded), then
      // the current precache version, then every older one still on the
      // device. The fallback chain is what makes an interrupted upgrade
      // harmless: a half-filled new version still serves every file.
      for (const name of [LIBRARY_CACHE, ...(await contentCaches())]) {
        const c = await caches.open(name);
        const old = await c.match(request);
        if (old) return old;
      }
    }

    try {
      const res = await fetch(request);
      if (res.ok && isContent(url.pathname)) {
        const copy = res.clone();
        const into = isPrecachedContent(url.href) ? CONTENT_CACHE : LIBRARY_CACHE;
        caches.open(into).then((c) => c.put(request, copy)).catch(() => { /* quota */ });
      }
      return res;
    } catch {
      if (request.mode === 'navigate') {
        const idx = await shell.match(abs('./index.html')) ?? await caches.match('./index.html');
        if (idx) return idx;
      }
      return Response.error();
    }
  })());
});

/* ------------------------------------------------------------------ */
/* The page talks to the worker                                        */
/* ------------------------------------------------------------------ */

self.addEventListener('message', (event) => {
  const msg = event.data;
  if (!msg || typeof msg !== 'object') return;

  if (msg.type === 'catos:sync') {
    // The page is idle and on a good connection: keep going.
    event.waitUntil(fillEverything());
    return;
  }

  if (msg.type === 'catos:status') {
    event.waitUntil((async () => {
      const state = await readState();
      const shell = await caches.open(SHELL_CACHE);
      const content = await caches.open(CONTENT_CACHE);
      const library = await caches.open(LIBRARY_CACHE);
      // Counted as "how many of the files we promised are present", not "how
      // many entries are in the cache" — the two diverge the moment a bank
      // file is read, and a progress bar past 100% is a progress bar nobody
      // believes again.
      const [coreMissing, shellMissing, contentMissing, libraryKeys] = await Promise.all([
        missingFrom(shell, CORE_FILES),
        missingFrom(shell, SHELL_FILES),
        missingFrom(content, CONTENT_FILES),
        library.keys(),
      ]);
      const reply = {
        type: 'catos:status',
        phase: state.phase ?? 'unknown',
        shellVersion: CACHE_VERSION,
        contentVersion: CONTENT_VERSION,
        core: { total: CORE_FILES.length, cached: CORE_FILES.length - coreMissing.length },
        shell: { total: SHELL_FILES.length, cached: SHELL_FILES.length - shellMissing.length },
        content: { total: CONTENT_FILES.length, cached: CONTENT_FILES.length - contentMissing.length },
        library: { cached: libraryKeys.length },
        lastError: state.lastError ?? null,
      };
      if (event.source) event.source.postMessage(reply);
      for (const client of await self.clients.matchAll()) client.postMessage(reply);
    })());
    return;
  }

  if (msg.type === 'catos:evict' && typeof msg.url === 'string') {
    // The page read this file and it was not what it claimed to be. Drop it
    // everywhere so the next read goes to the network.
    event.waitUntil((async () => {
      for (const name of await caches.keys()) {
        if (name === META_CACHE) continue;
        const c = await caches.open(name);
        await c.delete(msg.url).catch(() => { /* not there */ });
      }
    })());
  }
});
