/**
 * bake-motion.mjs — cut the living painting's patches out of the painting.
 *
 *   node tools/bake-motion.mjs
 *
 * Reads PATCHES from src/home/motion.js, and in headless Chrome cuts each one
 * out of assets/art/home-world-v1.png with its feathered edge baked into the
 * alpha (an ellipse, or a blurred polygon). The cuts are shelf-packed into
 * assets/art/home-motion-v1.png, and src/home/motion-atlas.js records where
 * each one went. Nothing is drawn: every pixel is the painting's own.
 *
 * Why bake instead of a CSS mask: each masked element costs the GPU its own
 * render pass, every frame. Thirty-six of them halved the frame rate on an
 * Intel HD 520; the same patches with their alpha baked in cost nothing
 * measurable.
 *
 * Rebake after changing PATCHES; tools/check-village-data.mjs fails until
 * the atlas matches.
 */
import { writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { serveRepo, launchChrome, REPO_ROOT } from './cdp-lite.mjs';

const ATLAS_JS = join(REPO_ROOT, 'src/home/motion-atlas.js');
const ATLAS_PNG = join(REPO_ROOT, 'assets/art/home-motion-v1.png');
const WIDTH = 1024, GUTTER = 2;

// motion.js imports the atlas module; give a first bake something to import.
if (!existsSync(ATLAS_JS)) writeFileSync(ATLAS_JS, "export const ATLAS = { src: '', w: 0, h: 0, at: [] };\n");

const server = await serveRepo();
const browser = await launchChrome({ width: 400, height: 300 });
try {
  await browser.open(`${server.url}assets/art/home-world-v1.png`, 600);
  const len = await browser.evaluate(`(async () => {
    const { PATCHES, rectOf, maskOf } = await import('/src/home/motion.js');
    const img = new Image(); img.src = '/assets/art/home-world-v1.png'; await img.decode();
    const rects = PATCHES.map(rectOf);
    // Shelf-pack, tallest first, ${WIDTH} wide with a ${GUTTER} px clear gutter.
    const order = rects.map((r, i) => i).sort((a, b) => rects[b].h - rects[a].h || a - b);
    const at = new Array(rects.length);
    let x = ${GUTTER}, y = ${GUTTER}, shelf = 0;
    for (const i of order) {
      const r = rects[i];
      if (x + r.w + ${GUTTER} > ${WIDTH}) { x = ${GUTTER}; y += shelf + ${GUTTER}; shelf = 0; }
      at[i] = [r.x, r.y, r.w, r.h, x, y];
      x += r.w + ${GUTTER}; shelf = Math.max(shelf, r.h);
    }
    const H = y + shelf + ${GUTTER};
    const atlas = document.createElement('canvas'); atlas.width = ${WIDTH}; atlas.height = H;
    const g = atlas.getContext('2d');
    PATCHES.forEach((p, i) => {
      const r = rects[i], m = maskOf(p, r);
      const cut = document.createElement('canvas'); cut.width = r.w; cut.height = r.h;
      const c = cut.getContext('2d');
      if (m.ellipse) {
        c.save(); c.translate(r.w / 2, r.h / 2); c.scale(r.w / 2, r.h / 2);
        const gr = c.createRadialGradient(0, 0, 0, 0, 0, 1);
        gr.addColorStop(0, '#000'); gr.addColorStop(m.solid, '#000'); gr.addColorStop(1, 'rgba(0,0,0,0)');
        c.fillStyle = gr; c.beginPath(); c.arc(0, 0, 1, 0, Math.PI * 2); c.fill(); c.restore();
      } else {
        c.filter = 'blur(' + m.blur + 'px)';
        c.beginPath(); m.points.forEach(([px, py], k) => (k ? c.lineTo(px, py) : c.moveTo(px, py))); c.closePath();
        c.fillStyle = '#000'; c.fill(); c.filter = 'none';
      }
      c.globalCompositeOperation = 'source-in';
      c.drawImage(img, -r.x, -r.y);
      g.drawImage(cut, at[i][4], at[i][5]);
    });
    window.__atlas = { w: ${WIDTH}, h: H, at };
    window.__png = atlas.toDataURL('image/png').split(',')[1];
    return window.__png.length;
  })()`);
  let b64 = '';
  for (let i = 0; i < len; i += 500000) b64 += await browser.evaluate(`window.__png.slice(${i}, ${i + 500000})`);
  const meta = await browser.evaluate('window.__atlas');
  writeFileSync(ATLAS_PNG, Buffer.from(b64, 'base64'));
  writeFileSync(ATLAS_JS, `/**
 * motion-atlas.js — GENERATED by tools/bake-motion.mjs; do not edit.
 * Where each patch of the living painting sits in assets/art/home-motion-v1.png:
 * [x, y, w, h] in the painting, then [ax, ay] in the atlas, in PATCHES order.
 */
export const ATLAS = {
  src: './assets/art/home-motion-v1.png', w: ${meta.w}, h: ${meta.h},
  at: [
${meta.at.map((a) => `    [${a.join(', ')}],`).join('\n')}
  ],
};
`);
  console.log(`bake-motion: ${meta.at.length} patches → ${meta.w}×${meta.h} atlas, ${Math.round(b64.length * 0.75 / 1024)} KB`);
} finally { browser.close(); server.close(); }
process.exit(0);
